easy_admin:
    entities:
        # List the entity class name you want to manage
        - App\Entity\User
        - App\Entity\Workshop
        - App\Entity\WorkshopApplicant
        - App\Entity\UserTeam
