version: 2

jobs:
  build:
    docker:
      - image: msvrtan/square:0.2.2
        environment:
          - APP_ENV=test
          - APP_DEBUG=1
          - APP_SECRET=123
          - DATABASE_DRIVER=pdo_mysql
          - DATABASE_SERVER_VERSION=5.7
          - DATABASE_HOST=127.0.0.1
          - DATABASE_PORT=3306
          - DATABASE_NAME=bob_test
          - DATABASE_USER=bob
          - DATABASE_PASSWORD=n0p455
      - image: mysql:5.7
        environment:
          - MYSQL_ROOT_PASSWORD=n0p455
          - MYSQL_DATABASE=bob_test
          - MYSQL_USER=bob
          - MYSQL_PASSWORD=n0p455
    working_directory: /var/www
    parallel: 1
    steps:
      - checkout

      - restore_cache:
          key: cache-v1-{{ checksum "composer.lock" }}

      - run:
          name: Composer install
          command: composer install -n --prefer-dist

      - run:
          name: Wait for MySQL to show up
          command: dockerize -wait tcp://localhost:3306 -timeout 1m

      - run:
          name: Update schema (add all tables project needs)
          command: php bin/console doctrine:migrations:migrate --no-interaction

      - run:
           name: PHP Mess Detector
           command: ./vendor/bin/phpmd src/ text phpmd.xml

      - run:
          name: PHPUnit
          command: ./vendor/bin/simple-phpunit

      - run:
          name: PHPstan
          command: ./vendor/bin/phpstan analyse -l 7 -c phpstan.neon src tests

      - run:
          name: Php-cs-fixer
          command: php vendor/bin/php-cs-fixer fix --dry-run --diff
          
      - save_cache:
          key: cache-v1-{{ checksum "composer.lock" }}
          paths:
            - ./vendor

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
