version: 2

jobs:
  build:
    docker:
      - image: msvrtan/square:0.2.2
        environment:
          - APP_ENV=test
          - APP_DEBUG=1
          - APP_SECRET=123
          - DATABASE_URL=mysql://bob:n0p455@127.0.0.1:3306/bob_test
          - TEST_DATABASE_URL=mysql://bob:n0p455@127.0.0.1:3306/bob_test
      - image: mysql:5.7
        environment:
          - MYSQL_ROOT_PASSWORD=n0p455
          - MYSQL_DATABASE=bob_test
          - MYSQL_USER=bob
          - MYSQL_PASSWORD=n0p455
    working_directory: /var/www
    parallel: 1
    steps:
      - checkout

      - restore_cache:
          key: cache-v1-{{ checksum "composer.lock" }}

      - run:
          name: Composer install
          command: composer install -n --prefer-dist

      - run:
          name: Wait for MySQL to show up
          command: dockerize -wait tcp://localhost:3306 -timeout 1m

      - run:
          name: Update schema (add all tables project needs)
          command: php bin/console doctrine:migrations:migrate --no-interaction

      - run:
          name: PHPUnit
          command: ./vendor/bin/simple-phpunit

      - save_cache:
          key: cache-v1-{{ checksum "composer.lock" }}
          paths:
            - ./vendor

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
